# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 1
  minor: 1
  revision: $[counter('rev', 0)]

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- powershell: |
    if ($(Build.SourceBranch).endswith("master"))
    { 
      Write-Host "##vso[task.LogIssue type=warning;] This is a master build"
      Write-Host "##vso[task.setvariable variable=isMain;]true"
    }
    elseif ($(Build.SourceBranch).endswith("merge"))
    {
      Write-Host "##vso[task.LogIssue type=warning;] This is a PR build, use system.pr.sourcebranch"    
      Write-Host "##vso[task.LogIssue type=warning;] PR.SourceBrance is $(System.PullRequest.SourceBranch)"
    }
    else
    {
      Write-Host "##vso[task.LogIssue type=warning;] CI to a sub branch"    
      Write-Host "##vso[task.LogIssue type=warning;] SourceBranch is $(Build.SourceBranch)"
    }
  displayName: 'Dump interesting variables'

- powershell: |
    Write-Host "##vso[task.LogIssue type=warning;] Is main is $(isMain)"
    [Reflection.Assembly]::LoadWithPartialName("System.Xml.Linq")
    $path = "PlanomaticPackage/Package.appxmanifest"
    $doc = [System.Xml.Linq.XDocument]::Load($path)
    $xIdentity = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Identity"
    $xProperties = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Properties"
    $xDisplayName = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}DisplayName"
    $xApplications = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Applications"
    $xApplication = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/foundation/windows10}Application"
    $xVisualElements = [System.Xml.Linq.XName]"{http://schemas.microsoft.com/appx/manifest/uap/windows10}VisualElements"
    $doc.Root.Element($xIdentity).Attribute("Version").Value = "$(major).$(minor).$(revision).0"
    $doc.Root.Element($xIdentity).Attribute("Name").Value = "Planomatic$(System.PullRequest.SourceBranch)"
    $doc.Root.Element($xProperties).Element($xDisplayName).Value = "Planomatic_$(System.PullRequest.SourceBranch)"
    $doc.Root.Element($xApplications).Element($xApplication).Element($xVisualElements).Attribute("DisplayName").Value = "Planomatic_$(System.PullRequest.SourceBranch)"
    $doc.Save($path)
  displayName: 'Setting Version and Branch Name in Package Manifest'

- powershell: |
   ((Get-Content -path PlanoWeb\plano.appinstaller -Raw) -replace '<msix_version>','$(major).$(minor).$(revision).0' `
                                                         -replace '<msix_name>','Planomatic_$(System.PullRequest.SourceBranch)_$(major).$(minor).$(revision).0.msix' `
                                                         -replace '<appinstaller_file>','plano_$(System.PullRequest.SourceBranch).appinstaller' `
                                                         -replace '<name>','Planomatic$(System.PullRequest.SourceBranch)') `
        | Set-Content -Path $(Build.ArtifactStagingDirectory)\plano_$(System.PullRequest.SourceBranch).appinstaller
  displayName: 'Updating Appinstaller file'

- task: MSBuild@1
  inputs:
    solution: $(solution)
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
    msbuildArguments: '/p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\Planomatic_$(System.PullRequest.SourceBranch)_$(major).$(minor).$(revision).0.msix /p:AppxPackageSigningEnabled=false'
  displayName: 'Build and Package'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'certificate.pfx'
  displayName: 'Download Secure PFX File'

- script: '"C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x86\signtool"
    sign /fd SHA256 /f $(Agent.TempDirectory)/certificate.pfx /p 1234 $(Build.ArtifactStagingDirectory)/Planomatic_$(System.PullRequest.SourceBranch)_$(major).$(minor).$(revision).0.msix'
  displayName: 'Sign MSIX Package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)\*'
    azureSubscription: 'planostorage'
    Destination: 'AzureBlob'
    storage: 'planomaticstorage'
    ContainerName: '$web'
    targetPath: 'branch'
    
